FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y build-essential libsnappy-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install \
    kafka-python \
    faker \
    python-snappy

WORKDIR /app

COPY producers /app/producers

CMD ["python","producers/run_all.py"]